In [5]:
import numpy as np 
arr = np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [6]:
arr = np.zeros((4,6))
print(arr)
arr[2,:] =99
print(arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [7]:
arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print(arr)
res = arr[arr>50]
print(res)

[12 45  7 19 88  3 56 91 24 67]
[88 56 91 67]


In [10]:
arr = np.eye(5)
print(arr)
np.fill_diagonal(arr,[10,20,30,40,50])
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


In [39]:
x = np.arange(1,21).reshape(4,5)
print(x)
x[2:,:] #last two rows
x[:,2] #third col
x[:3,2:]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [41]:
a = np.array([1, 2, 3, 4])
b = np.array([[10], [20], [30]])
add = a+b
print(a+b)
print(add.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


In [42]:
data = np.array([150, 220, 90, 30, 180, 45])
min_data = data.min()
max_data = data.max()
nor = (data - min_data) / (max_data - min_data)
print(nor)

[0.63157895 1.         0.31578947 0.         0.78947368 0.07894737]


In [43]:
data = np.array([150, 220, 90, 30, 180, 45])
data2 = np.mean(data)
std = np.std(data)
standardized_data = (data - data2) / std
print(standardized_data)

[ 0.44258247  1.44736428 -0.41865909 -1.27990064  0.87320324 -1.06459025]


In [49]:
mat = np.array([
    [4, 8, 1, 12],
    [7, 3, 9, 5],
    [11, 2, 6, 10],
    [15, 0, 14, 13]
])
#Compute the mean of each row
meanOfRow = np.mean(mat, axis=1)
print(meanOfRow)
print('-----------------------------------------------')
#b. Compute the sum of each column
SumOfCol = np.sum(mat, axis=0)
print(SumOfCol)
print('-----------------------------------------------')
#c. Maximum value and its position
maxval = np.max(mat) 
print(maxval)
maxpos = np.unravel_index(np.argmax(mat), mat.shape) 
print(maxpos)

[ 6.25  6.    7.25 10.5 ]
-----------------------------------------------
[37 13 30 40]
-----------------------------------------------
15
(np.int64(3), np.int64(0))


In [53]:
#Reshape the array np.arange(36) into a 3D array of shape (3, 4, 3).
arrThree = np.arange(36)
print(arrThree)
arrThree = np.arange(36).reshape(3, 4, 3)
print(arrThree)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [55]:
#Reverse the order of rows and columns (flip both).
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
print('-----------------------------------------------')
flipped_arr = arr[::-1, ::-1]
print(flipped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------------
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [56]:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])
age25to40 = (ages >= 25) & (ages <= 40)
result = names[age25to40]
print(result)

['Lina' 'Khaled' 'Hassan']


In [57]:
print(ages)
ages[ages < 20] = 20
print(ages)

[23 45 19 34 28 51 17 39]
[23 45 20 34 28 51 20 39]


In [58]:
np.random.seed(123)
randomArr = np.random.randint(1, 101, size=(6, 6))
print(randomArr)

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [59]:
normalDist = np.random.normal(loc=100, scale=15, size=10)
print(normalDist)

[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


In [60]:
colors = ["red", "blue", "green", "yellow", "purple"]
selClo = np.random.choice(colors, size=3, replace=False)
print(selClo)

['blue' 'yellow' 'purple']


In [63]:
numbers = np.arange(1, 21)
print(numbers)
print('-----------------------------------------------')
np.random.shuffle(numbers)
print(numbers)
print('-----------------------------------------------')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
-----------------------------------------------
[ 9 10  3  8 14  1  6 17 20  5  4 11  2 16 12 18 13 19  7 15]
-----------------------------------------------
